### ISSUE TITLE
Consider new name for Load EEPROM

### ISSUE THREAD

**Issue by PropGit** [parallaxinc/Propeller-Tool#10]
Maybe something that applies to both P1 and P2.

**Comment by JonMcPhalen** [comment]
If the device type (P1 or P2) is known, can that be made dynamic?

P1) Load EEPROM
P2) Load FLASH

**Comment by PropGit** [comment]
Great idea - it seems like it would be known at all the times that would matter, both on the source view and in the info view.

**Comment by PropGit** [comment]
Implemented in v2.1.
