### ISSUE TITLE
DEBUG Windows Open then Auto Close

### ISSUE THREAD

**Issue by JonMcPhalen** [parallaxinc/Propeller-Tool#120]
OS = Win 10 Pro
Memory = 64G

When running Parallax DEBUG demos, the DEBUG windows open and then immediately close. The P2 is still streaming data as evidenced by the flashing LED on the Prop Plug.

**Comment by PropGit** [comment]
The windows are likely opening then quickly switching to behind the Propeller Tool window.  Unintentionally, of course.

Working on find the solution to this.

**Comment by PropGit** [comment]
Fixed in v2.5.1.
