### ISSUE TITLE
Make Enable Debug Status Persistent Between Sessions

### ISSUE THREAD

**Issue by JonMcPhalen** [parallaxinc/Propeller-Tool#123]
On restarting Propeller Tool, the Enable Debug state is set to ON by default; this gets in the way as soon as I try to download something that uses PST. Please make this state persistent between sessions so that I don't have to turn it off every time I restart Propeller Tool (which is frequent given crashes probably caused by memory leaks).

The Enable Debug state should also be part of the toolbar which is right around the corner, right? :)

**Comment by PropGit** [comment]
Thanks @JonMcPhalen.  (I thought I had recorded this as an issue already, but don't see it; regardless, it's what was intended)

They'll also be an additional enhancement that makes this issue mostly mute, related to issue #112.  I'd requested the P2 compiler be enhanced to automatically step back to debug mode _off_ if the source being compiled doesn't contain executable DEBUG() statements.  That request may or may not still happen.  For now, I'll resolve it furth in the Propeller Tool itself; the current behavior is just temporary.

Yes, Enable Debug will be a button on the toolbar.  Yes, it's right around the corner.

**Comment by PropGit** [comment]
Setting is now saved in v2.5.2 and restored at the start of the next session.

Also of note, as indicated earlier, an enhancement to the same version makes the experience much smoother regardless of this issue: with Debug Mode on, if the objects being compiled do not contain executable DEBUGs, no debug-related error occurs and instead the P2 application is built without the debug subsystem included (just like compiling with Debug Mode off).  A notice appears on the status bar when this automatic behavior was employed.
