### ISSUE TITLE
Adjust Debug Clock Frequency sensitivity to allow documentation view of subobjects with debug

### ISSUE THREAD

**Issue by PropGit** [parallaxinc/Propeller-Tool#138]
From @ChipGracey:
> We need to change the debug clock frequency sensitivity so that we only care if they are trying to download that file. When I try to make documentation View of my file oh, it gets mad because I don't have a clock frequency set up and I have debug statements, but the parent is always going to supply the clock frequency. So, we need to ignore it, and less the user wants to download.

**Comment by PropGit** [comment]
@ChipGracey - Do you mean this change will be done in the compiler (through a flag so it knows when...)  or do you mean in the Propeller Tool (we should automatically compile without debug) when... we're only compiling for documentation purposes?

**Comment by ChipGracey** [comment]
Ah, for documentation purposes, you could just compile without DEBUG. Yes,
that would be better.

**Comment by PropGit** [comment]
Okay, that's what we'll do then.

**Comment by PropGit** [comment]
Fixed in v2.5.3.
