### ISSUE TITLE
Text editing becomes less responsive while debugger is active

### ISSUE THREAD

**Issue by Wuerfel21** [parallaxinc/Propeller-Tool#139]
While the debug message window is open, typing into the editor becomes somewhat unresponsive, even if there is no debug activity.

Scrolling also becomes very choppy.

**Comment by PropGit** [comment]
Thanks @Wuerfel21.  Turns out, this is a duplicate of issue #137 I just entered this morning, although your title is much better than mine for the general public. 

This issue will be addressed soon.

**Comment by PropGit** [comment]
This is fixed in v2.5.3.
