### ISSUE TITLE
Syntax Highlighting with Inline PASM2 

### ISSUE THREAD

**Issue by JonMcPhalen** [parallaxinc/Propeller-Tool#148]
The pointer registers are not highlighted when used in inline PASM2 (they are in dat sections). 
This is a low-priority issue.

![image](https://user-images.githubusercontent.com/4042568/114241081-76326100-993d-11eb-9c6f-6bac02503c84.png)

**Comment by PropGit** [comment]
Fixed in v2.6.4.
