### ISSUE TITLE
Create new file with P2 template does not change project to P2 "mode"

### ISSUE THREAD

**Issue by VonSzarvas** [parallaxinc/Propeller-Tool#164]
Steps...

1. Start Propeller Tool
2. File/New file with P2 Template
3. Click Save (and observe the file type is P1 / .spin)

**Comment by PropGit** [comment]
Fixed in v2.9.0.0.

Now it converts the tabname to reflect the mode ("P1: " or "P2: "), compiles and syntax highlights properly, and saves with the appropriate default extension.
