### ISSUE TITLE
Change to REPEAT breaks production code

### ISSUE THREAD

**Issue by JonMcPhalen** [parallaxinc/Propeller-Tool#170]
In the P1 and Propeller Tool up to 2.70, when a user control variable was used with the repeat, the value of that variable would be the end value plus or minus one (depending on starting value). This behavior allows programmers to verify that the loop ran all the way through without early termination. In Propeller Tool 2.9.2 the control variable is left at the ending value.

This means 
1) P2 code and P1 loop code now differ
2) The programmer will be forced to add a test variable to verify the loop ran all the way through (affecting code space and speed)

**Comment by PropGit** [comment]
Issue fixed in Propeller Tool V2.9.3 - REPEAT var is left at end value +/- step value (as it was originally prior to v2.7.0).
