### ISSUE TITLE
FSRW test goes sideways after load..

### ISSUE THREAD

**Issue by GitRayman** [parallaxinc/Propeller-Tool#21]
The fsrw test#2 code from here:  http://forums.parallax.com/discussion/171619/

Appears to compile and load, but something goes wrong immediately after loading and appears to reboot...

This file works with both PNut and Fastspin.

**Comment by PropGit** [comment]
Have you tried loading to flash to see if it runs properly after the apparent reboot?  Just curious; it should work just like with PNut. 

This is one the P2-ES Rev B with a prewritten microSD card inserted?

**Comment by GitRayman** [comment]
I played with the jumpers to load to flash and the boot from flash...
Same thing happens when booting from flash.
I guess that means it compiled wrong. 
Not sure how that is possible.  Works with PNut...

**Comment by GitRayman** [comment]
I can see it load up about 1/4 of the VGA screen from the bitmap on the uSD card and then stop.

**Comment by GitRayman** [comment]
All the files needed to reproduce are in the top link.  Just copy bitmap2.bmp to uSD and set all jumpers off, except P59 pullup.

**Comment by GitRayman** [comment]
Ok, yes, looks like file directive is broke.  Changing to this works:

orgh        
BitmapFile 'something to show before load is complete and also storage for bitmap
                'file "TestPat1.bmp" '640 x 480, 8bpp bitmap
                byte 0[350000] 'a little padding just in case metadata and/or block size makes SD file bigger

**Comment by PropGit** [comment]
@GitRayman I believe I have fixed it.  Can you retest your fsrw test#2.spin2 object, and any other examples you have, to verify?  Use that attached version of Propeller Tool v2.1.1.0-Alpha.


[Propeller_v2.1.1.0-Alpha.zip](https://github.com/parallaxinc/Propeller-Tool/files/4781936/Propeller_v2.1.1.0-Alpha.zip)

**Comment by GitRayman** [comment]
Thanks.  Just tried test#2.spin2 and it works!

**Comment by PropGit** [comment]
You're welcome, and thank you too.  The problem was something I had marked as questionable in code but failed to get back to before first alpha, and the result of the error showed up in a way I didn't expect.  I'm glad to get confirmation that it works now.  They'll be another official Alpha on 6/17 that includes this fix.

**Comment by PropGit** [comment]
This is included in v2.2.0.0-Alpha.
