### ISSUE TITLE
SPIN2/cogspin method

### ISSUE THREAD

**Issue by c0ded0g** [parallaxinc/Propeller-Tool#26]
code doesn't seem to execute past the first COGSPIN() call

the SPIN2 code in the new cog executes but any code after the COGSPIN call in the main cog doesn't execute ... or am I incorrectly using this method?

e.g.
PUB main ()
  CLKSET(oscmode1, freq)
  COGSPIN(cogT1, testLeds(), @stack1)
  ... code here doesn't execute

 PUB testLeds()
  ... code here executes OK ...

**Comment by PropGit** [comment]
I was able to get a similar program working correctly (see below).  The problem could be your value for _cogT1_, the size of your _Stack1_, or the code that doesn't seem to execute.  I doubt that the _CLKSET()_ could be at fault, but I commented it out in my case to use the default.

For example, if _cogT1_ = 0, then the _COGSPIN()_ will restart your first cog (the one that's executing the _main()_ method) and instead run the _testLeds()_ method in its place.  If _Stack1_ is too small, the newly-started cog's Spin interpreter may inadvertently be overwriting memory (not sure that would cause a problem in this specific case).  There may be an indention problem in the code that doesn't seem to execute, or perhaps it's not in a loop (executing just once, too fast to see), etc.

```
CON
  cogT1 = 1  'Use NEWCOG for next available cog

VAR
  long Stack1[16]
    
PUB main()
'  CLKSET(oscmode1, freq)
  COGSPIN(cogT1, testLeds(), @Stack1)

  {Blink Cog ID-based LED with 1-second cadence}
  repeat
    pintoggle(cogid()+56)
    waitms(1000)  
    

PUB testLeds() | PinNum
{Blink Cog ID-based LED randomly}
  repeat
    pinwrite(cogid()+56, getrnd())
    waitms(100)
```

**Comment by c0ded0g** [comment]
Thanks PropGit, issue resolved. 

The problem was my understanding of COGSPIN(), where I was using an uninitialized var cogT1 (i.e. = 0). I am using the Google Docs Spin2 documentation as a guide to the available methods, and understandably it is incomplete - but are there any other SPIN2 references you are aware of that we can use? 

to elaborate, the Google Docs Spin2 doc (v34s) provides only this:
COGSPIN(CogNum, Method({Pars}), StkAddr):
Start Spin2 method in a cog, returns cog's ID if used as an expression element, -1 = no cog free 

... there's no indication of how to use the first parameter, what its allowed values are, or what they mean. I assume there might be other references out there?

Thanks for taking the time to explain this above, it is very much appreciated.

**Comment by PropGit** [comment]
@c0ded0g Currently, that's the only Spin2 documentation and I too had to experiment and ask questions.

I've found out that for the CogNum parameter, it takes a 5-bit value.  The first 4 bits (3:0) indicate the ID of the cog to start (Cog 0 through Cog 15 [where only values 0 through 7 makes sense to use unless this were a future Propeller 2 with 16 cogs]) corresponding to bit patterns %0000 through %1111.  The last bit (4) indicates to start the next available cog (if the bit pattern is %10000) or next available pair of cogs [_even_ next to _odd_ ID] (if the bit pattern in %10001).
