### ISSUE TITLE
occurance

### ISSUE THREAD

**Issue by c0ded0g** [parallaxinc/Propeller-Tool#33]
finally might be a good time to address this one ... after almost 10 years ...

https://forums.parallax.com/discussion/126031/occurance-occurrence-occurence/p1

cheers,

**Comment by PropGit** [comment]
Thanks @c0ded0g!  

Yes indeed, that one has been there a long time and I never knew about it.

**Comment by PropGit** [comment]
Fixed.  Will be released in Alpha 4.

There were 12 occurrences of 'occurances' in the source: in comments, enumerations, and hints.
