### ISSUE TITLE
Remove Trailing Spaces from Lines on Save

### ISSUE THREAD

**Issue by JonMcPhalen** [parallaxinc/Propeller-Tool#36]
Propeller Tool converts tabs to spaces and spaces can sometimes be hanging at the end of a line -- unseen. For those of us copying from the editor to other documents this can be a small problem. 

Suggestion: One saving a file, remove any trailing white space from each line.

**Comment by PropGit** [comment]
Noted.

**Comment by PropGit** [comment]
The editor is already set to remove trailing spaces; yet I've seen this very result myself as well.  Need to dive into it further.

**Comment by PropGit** [comment]
The underlying editor object was handling this in a way we don't want; it was only removing trailing spaces only from the current line that the cursor is on.  This perhaps was intended to clean up trailing spaces left by editing activity combined with cursor movements; however, it obviously doesn't address the need this issue raised.

Fixed - it now processes the entire file, removing trailing spaces on every line, at the moment of saving to the filesystem.  This feature will appears in v2.3.0.0 Alpha.
