### ISSUE TITLE
Alpha 2.3.0.0 Compiles with DEBUG But Won't Run DEBUG

### ISSUE THREAD

**Issue by JonMcPhalen** [parallaxinc/Propeller-Tool#39]
I loaded one of Chip's DEBUG demos into Alpha 2.3.0.0. 
-- compiles fine with F10
-- if Ctrl+F10 is used, a "Cannot find source file: UntitledX" dialog is displayed

**Comment by Wuerfel21** [comment]
CTRL+F10 is still "Load top file" to RAM (and I'd like it to stay that way)

Maybe ALT+F10 for load with debug (and CTRL+ALT+F10 for load top with debug?)

**Comment by PropGit** [comment]
> I loaded one of Chip's DEBUG demos into Alpha 2.3.0.0.
> -- compiles fine with F10
> -- if Ctrl+F10 is used, a "Cannot find source file: UntitledX" dialog is displayed

Ctrl+F10 is looking for a top file, which doesn't exist.  Maybe the Top file is something you had set previously (a while ago)?

**Comment by PropGit** [comment]
> CTRL+F10 is still "Load top file to RAM" (and I'd like it to stay that way)
> 
> Maybe ALT+F10 for load with debug (and CTRL+ALT+F10 for load top with debug?)

I agree.  Some other keyboard combination for compiling with Debug.

The latest P2 compiler is in there, but there are no debugging links added yet.

**Comment by JonMcPhalen** [comment]
I never use the "Top Object" feature and forgot about it until your presentation today. Sorry for the bogus report.

**Comment by PropGit** [comment]
No problem.  I'll close this one but have taken note of @Wuerfel21's suggestion to remap Chip's "debug" commands to a different key combination, so as not to upset the long-set precedent that Propeller Tool users are familiar with.
