### ISSUE TITLE
Just tested 2.4r3 on my system and the font did not install.

### ISSUE THREAD

**Issue by cjmoorejr** [parallaxinc/Propeller-Tool#47]
Just tested 2.4r3 on my system and the font did not install.  Tried it twice.  The second time after a reboot.  I was able to drag the font into the windows/font directory and it worked.  I'm including my particulars on my system.

Microsoft Surface Pro 7
Edition:  Windows 10 Home
Version:  20H2
OS Build:  19042.630

I installed on D: instead of C:

Maybe the install script is trying to copy the font from the C: drive instead of the drive (D:) I specified at the beginning of the install process.

_Originally posted by @cjmoorejr in https://github.com/parallaxinc/Propeller-Tool/issues/46#issuecomment-733271896_

Sorry about reposting this.  I wasn't sure if additional comments in a CLOSED issue would reopen it.

**Comment by PropGit** [comment]
No problem.  They don't cause it to reopen, but the system notified me regardless.  I'll close this and reopen the other.
