### ISSUE TITLE
Can't Open the P1 Help Files

### ISSUE THREAD

**Issue by cjmoorejr** [parallaxinc/Propeller-Tool#49]
These worked under 1.3.2 and the Alpha versions.  Doesn't seen to work on 2.4r3.  I'm running Windows 10 20H2.  The Windows Edge browser is the default PDF viewer for any of PDF files on my system.  I even installed the Adobe Reader Touch app (I'm using a Surface) but Propeller Tool won't open any of the P1 help files with either of these viewers.  How exactly are these menu items trying to open the PDF files?

![2020-11-26-Propeller-Tool-02](https://user-images.githubusercontent.com/36820917/100416917-4301cc00-3045-11eb-8dcb-c4afc9ae3e7a.PNG)

**Comment by PropGit** [comment]
Fixed in v2.4.1.
